//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ANN
{
    using System;
    using System.Collections.Generic;
    
    public partial class coursecurrency
    {
        public int coursecurrency_id { get; set; }
        public decimal course { get; set; }
        public decimal substractcourse { get; set; }
        public string namecurrency { get; set; }
        public Nullable<System.DateTime> datecourse { get; set; }
    }
}
